spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: tyaa74521
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8080
  servlet:
    context-path: /sell

wechat:
  appId: wx484ce8b92a084a0b
  apiKey: 51VH03mx78j0gindrijxJYs6qJY76q8Y
  appSecret: c02eeb52ebfa3fd99a94f8dc8e412628
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1502953181
  notifyUrl:  http://sell.natapp4.cc/sell/pay/notify